# Remove the 'version' field at the top of the file

services:
  jobtracker-api:
    build: .
    ports:
      - "${API_PORT:-5052}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=jobtracker-db;Database=JobTracker;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - API_PORT=80
    depends_on:
      jobtracker-db:
        condition: service_healthy
    restart: always

  jobtracker-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: JobTracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data: