name: Build and Deploy JobTracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_ENVIRONMENT: 'Production'
  DOCKER_IMAGE_NAME: 'job-tracker-api'
  DOCKER_REGISTRY: 'ghcr.io'
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  DOCKER_CONTAINER_NAME: 'job-tracker-api-container'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Environment Validation
        run: |
          # Simple validation to ensure required secrets exist
          if [ -z "${{ secrets.DB_HOST }}" ]; then echo "Missing DB_HOST secret"; exit 1; fi
          if [ -z "${{ secrets.DB_USERNAME }}" ]; then echo "Missing DB_USERNAME secret"; exit 1; fi
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then echo "Missing DB_PASSWORD secret"; exit 1; fi
          if [ -z "${{ secrets.DB_DATABASE }}" ]; then echo "Missing DB_DATABASE secret"; exit 1; fi
          if [ -z "${{ secrets.API_PORT }}" ]; then echo "Missing API_PORT secret"; exit 1; fi
          if [ -z "${{ secrets.JWT_SECRET }}" ]; then echo "Missing JWT_SECRET secret"; exit 1; fi
          if [ -z "${{ secrets.JWT_ISSUER }}" ]; then echo "Missing JWT_ISSUER secret"; exit 1; fi
          if [ -z "${{ secrets.JWT_AUDIENCE }}" ]; then echo "Missing JWT_AUDIENCE secret"; exit 1; fi
          if [ -z "${{ secrets.GOOGLE_CLIENT_ID }}" ]; then echo "Missing GOOGLE_CLIENT_ID secret"; exit 1; fi
          if [ -z "${{ secrets.GOOGLE_SECRET }}" ]; then echo "Missing GOOGLE_SECRET secret"; exit 1; fi
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then echo "Missing GEMINI_API_KEY secret"; exit 1; fi
          if [ -z "${{ secrets.GEMINI_API_ENDPOINT }}" ]; then echo "Missing GEMINI_API_ENDPOINT secret"; exit 1; fi
          if [ -z "${{ secrets.SSH_HOST }}" ]; then echo "Missing SSH_HOST secret"; exit 1; fi
          if [ -z "${{ secrets.SSH_USERNAME }}" ]; then echo "Missing SSH_USERNAME secret"; exit 1; fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then echo "Missing SSH_PRIVATE_KEY secret"; exit 1; fi
          echo "All required secrets are present"

      - name: Create Production Configuration
        run: |
          # Create a valid JSON configuration file
          cat > appsettings.Production.json << EOF
          {
            "ConnectionStrings": {
              "DefaultConnection": "Host=${{ secrets.DB_HOST }};Port=5432;Database=${{ secrets.DB_DATABASE }};Username=${{ secrets.DB_USERNAME }};Password=${{ secrets.DB_PASSWORD }};"
            },
            "Jwt": {
              "Key": "${{ secrets.JWT_SECRET }}",
              "Issuer": "${{ secrets.JWT_ISSUER }}",
              "Audience": "${{ secrets.JWT_AUDIENCE }}"
            },
            "Authentication": {
              "Google": {
                "ClientId": "${{ secrets.GOOGLE_CLIENT_ID }}",
                "ClientSecret": "${{ secrets.GOOGLE_SECRET }}"
              }
            },
            "Gemini": {
              "ApiKey": "${{ secrets.GEMINI_API_KEY }}",
              "ApiEndpoint": "${{ secrets.GEMINI_API_ENDPOINT }}"
            },
            "API_PORT": "${{ secrets.API_PORT }}",
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*"
          }
          EOF
          
          # Verify that the JSON is valid
          jq . appsettings.Production.json
          
          # Show the file (with sensitive information masked)
          cat appsettings.Production.json | sed 's/"Key": "[^"]*"/"Key": "***"/g' | sed 's/"ClientSecret": "[^"]*"/"ClientSecret": "***"/g' | sed 's/"ApiKey": "[^"]*"/"ApiKey": "***"/g' | sed 's/"Password=[^;]*;/"Password=***;/g'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Prepare Docker build context
        run: |
          # Create a directory for the Docker build context
          mkdir -p docker-context
          
          # Copy necessary files
          cp -r . docker-context/
          
          # Ensure the production config is properly placed
          cp appsettings.Production.json docker-context/

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker-context
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo "Image digest ${{ steps.meta.outputs.digest }}"

      - name: Deploy to Development Environment
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # Create directory for config file if it doesn't exist
            mkdir -p ~/job-tracker-config
            
            # Log in to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            # Pull the latest image
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            
            # Stop and remove the old container if it exists
            if docker ps -a | grep -q ${{ env.DOCKER_CONTAINER_NAME }}; then
              docker stop ${{ env.DOCKER_CONTAINER_NAME }} || true
              docker rm ${{ env.DOCKER_CONTAINER_NAME }} || true
            fi
            
            # Create a volume for persistent configuration
            cat > ~/job-tracker-config/appsettings.Production.json << 'EOF'
            {
              "ConnectionStrings": {
                "DefaultConnection": "Host=${{ secrets.DB_HOST }};Port=5432;Database=${{ secrets.DB_DATABASE }};Username=${{ secrets.DB_USERNAME }};Password=${{ secrets.DB_PASSWORD }};"
              },
              "Jwt": {
                "Key": "${{ secrets.JWT_SECRET }}",
                "Issuer": "${{ secrets.JWT_ISSUER }}",
                "Audience": "${{ secrets.JWT_AUDIENCE }}"
              },
              "Authentication": {
                "Google": {
                  "ClientId": "${{ secrets.GOOGLE_CLIENT_ID }}",
                  "ClientSecret": "${{ secrets.GOOGLE_SECRET }}"
                }
              },
              "Gemini": {
                "ApiKey": "${{ secrets.GEMINI_API_KEY }}",
                "ApiEndpoint": "${{ secrets.GEMINI_API_ENDPOINT }}"
              },
              "API_PORT": "${{ secrets.API_PORT }}",
              "Logging": {
                "LogLevel": {
                  "Default": "Information",
                  "Microsoft.AspNetCore": "Warning"
                }
              },
              "AllowedHosts": "*"
            }
            EOF
            
            # Start the new container with volume mount for config
            docker run -d \
              --name ${{ env.DOCKER_CONTAINER_NAME }} \
              --network host \
              --restart unless-stopped \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e API_PORT=${{ secrets.API_PORT }} \
              -v ~/job-tracker-config/appsettings.Production.json:/app/appsettings.Production.json \
              ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            
            # Verify container is running
            docker ps | grep ${{ env.DOCKER_CONTAINER_NAME }}
            
            # Check logs for startup errors
            echo "Container logs:"
            sleep 5
            docker logs ${{ env.DOCKER_CONTAINER_NAME }}
            
            # Clean up old images
            docker system prune -f

      - name: Clean up
        if: always()
        run: |
          rm -f appsettings.Production.json
          echo "Cleaned up sensitive files"